### ISSUE TITLE
Failed at devrantcli@1.0.0 start script

### ISSUE THREAD

**Issue by akasoggybunz** [kurtr/devRantCLI#1]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink C:\Program Files (x86)\nodejs\\node.exe
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart devrantcli@1.0.0
7 info start devrantcli@1.0.0
8 verbose unsafe-perm in lifecycle true
9 info devrantcli@1.0.0 Failed to exec start script
10 verbose stack Error: devrantcli@1.0.0 start: `node app/index.js`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid devrantcli@1.0.0
12 verbose cwd U:\devRantCLI
13 error Windows_NT 6.3.9600
14 error argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
15 error node v0.12.2
16 error npm  v2.7.4
17 error code ELIFECYCLE
18 error devrantcli@1.0.0 start: `node app/index.js`
18 error Exit status 1
19 error Failed at the devrantcli@1.0.0 start script 'node app/index.js'.
19 error This is most likely a problem with the devrantcli package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     node app/index.js
19 error You can get their info via:
19 error     npm owner ls devrantcli
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

**Comment by kurtr** [comment]
Sorry for the late response. This error is most likely caused by running an incorrect version of node. I am currently using v7.10.1. Try using nvm to update / switch versions.
